// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "system.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MsgHeartItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgHeartItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgHeart_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgHeart_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgTestBool_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgTestBool_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_system_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_system_2eproto() {
  protobuf_AddDesc_system_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "system.proto");
  GOOGLE_CHECK(file != NULL);
  MsgHeartItem_descriptor_ = file->message_type(0);
  static const int MsgHeartItem_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeartItem, val_),
  };
  MsgHeartItem_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgHeartItem_descriptor_,
      MsgHeartItem::default_instance_,
      MsgHeartItem_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgHeartItem),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeartItem, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeartItem, _is_default_instance_));
  MsgHeart_descriptor_ = file->message_type(1);
  static const int MsgHeart_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeart, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeart, item_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeart, guid_),
  };
  MsgHeart_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgHeart_descriptor_,
      MsgHeart::default_instance_,
      MsgHeart_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgHeart),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeart, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgHeart, _is_default_instance_));
  MsgTestBool_descriptor_ = file->message_type(2);
  static const int MsgTestBool_offsets_[32] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_5_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_6_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_7_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_8_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_9_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_10_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_11_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_12_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_13_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_14_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_15_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_16_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_17_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_18_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_19_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_20_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_21_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_22_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_23_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_24_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_25_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_26_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_27_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_28_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_29_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_30_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_31_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, test_32_),
  };
  MsgTestBool_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgTestBool_descriptor_,
      MsgTestBool::default_instance_,
      MsgTestBool_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgTestBool),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgTestBool, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_system_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgHeartItem_descriptor_, &MsgHeartItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgHeart_descriptor_, &MsgHeart::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgTestBool_descriptor_, &MsgTestBool::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_system_2eproto() {
  delete MsgHeartItem::default_instance_;
  delete MsgHeartItem_reflection_;
  delete MsgHeart::default_instance_;
  delete MsgHeart_reflection_;
  delete MsgTestBool::default_instance_;
  delete MsgTestBool_reflection_;
}

void protobuf_AddDesc_system_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_system_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014system.proto\"\033\n\014MsgHeartItem\022\013\n\003val\030\001 "
    "\001(\t\"C\n\010MsgHeart\022\014\n\004name\030\002 \001(\t\022\033\n\004item\030\001 "
    "\001(\0132\r.MsgHeartItem\022\014\n\004guid\030\003 \001(\005\"\244\004\n\013Msg"
    "TestBool\022\016\n\006test_1\030\001 \001(\010\022\016\n\006test_2\030\002 \001(\010"
    "\022\016\n\006test_3\030\003 \001(\010\022\016\n\006test_4\030\004 \001(\010\022\016\n\006test"
    "_5\030\005 \001(\010\022\016\n\006test_6\030\006 \001(\010\022\016\n\006test_7\030\007 \001(\010"
    "\022\016\n\006test_8\030\010 \001(\010\022\016\n\006test_9\030\t \001(\010\022\017\n\007test"
    "_10\030\n \001(\010\022\017\n\007test_11\030\013 \001(\010\022\017\n\007test_12\030\014 "
    "\001(\010\022\017\n\007test_13\030\r \001(\010\022\017\n\007test_14\030\016 \001(\010\022\017\n"
    "\007test_15\030\017 \001(\010\022\017\n\007test_16\030\020 \001(\010\022\017\n\007test_"
    "17\030\021 \001(\010\022\017\n\007test_18\030\022 \001(\010\022\017\n\007test_19\030\023 \001"
    "(\010\022\017\n\007test_20\030\024 \001(\010\022\017\n\007test_21\030\025 \001(\010\022\017\n\007"
    "test_22\030\026 \001(\010\022\017\n\007test_23\030\027 \001(\010\022\017\n\007test_2"
    "4\030\030 \001(\010\022\017\n\007test_25\030\031 \001(\010\022\017\n\007test_26\030\032 \001("
    "\010\022\017\n\007test_27\030\033 \001(\010\022\017\n\007test_28\030\034 \001(\010\022\017\n\007t"
    "est_29\030\035 \001(\010\022\017\n\007test_30\030\036 \001(\010\022\017\n\007test_31"
    "\030\037 \001(\010\022\017\n\007test_32\030  \001(\010B\002H\001b\006proto3", 675);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "system.proto", &protobuf_RegisterTypes);
  MsgHeartItem::default_instance_ = new MsgHeartItem();
  MsgHeart::default_instance_ = new MsgHeart();
  MsgTestBool::default_instance_ = new MsgTestBool();
  MsgHeartItem::default_instance_->InitAsDefaultInstance();
  MsgHeart::default_instance_->InitAsDefaultInstance();
  MsgTestBool::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_system_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_system_2eproto {
  StaticDescriptorInitializer_system_2eproto() {
    protobuf_AddDesc_system_2eproto();
  }
} static_descriptor_initializer_system_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgHeartItem::kValFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgHeartItem::MsgHeartItem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgHeartItem)
}

void MsgHeartItem::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgHeartItem::MsgHeartItem(const MsgHeartItem& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgHeartItem)
}

void MsgHeartItem::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgHeartItem::~MsgHeartItem() {
  // @@protoc_insertion_point(destructor:MsgHeartItem)
  SharedDtor();
}

void MsgHeartItem::SharedDtor() {
  val_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgHeartItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgHeartItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgHeartItem_descriptor_;
}

const MsgHeartItem& MsgHeartItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_system_2eproto();
  return *default_instance_;
}

MsgHeartItem* MsgHeartItem::default_instance_ = NULL;

MsgHeartItem* MsgHeartItem::New(::google::protobuf::Arena* arena) const {
  MsgHeartItem* n = new MsgHeartItem;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgHeartItem::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgHeartItem)
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MsgHeartItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgHeartItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string val = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_val()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->val().data(), this->val().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MsgHeartItem.val"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgHeartItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgHeartItem)
  return false;
#undef DO_
}

void MsgHeartItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgHeartItem)
  // optional string val = 1;
  if (this->val().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val().data(), this->val().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgHeartItem.val");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->val(), output);
  }

  // @@protoc_insertion_point(serialize_end:MsgHeartItem)
}

::google::protobuf::uint8* MsgHeartItem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgHeartItem)
  // optional string val = 1;
  if (this->val().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val().data(), this->val().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgHeartItem.val");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->val(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MsgHeartItem)
  return target;
}

int MsgHeartItem::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MsgHeartItem)
  int total_size = 0;

  // optional string val = 1;
  if (this->val().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->val());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgHeartItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MsgHeartItem)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgHeartItem* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgHeartItem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MsgHeartItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MsgHeartItem)
    MergeFrom(*source);
  }
}

void MsgHeartItem::MergeFrom(const MsgHeartItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MsgHeartItem)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.val().size() > 0) {

    val_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_);
  }
}

void MsgHeartItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MsgHeartItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgHeartItem::CopyFrom(const MsgHeartItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgHeartItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgHeartItem::IsInitialized() const {

  return true;
}

void MsgHeartItem::Swap(MsgHeartItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgHeartItem::InternalSwap(MsgHeartItem* other) {
  val_.Swap(&other->val_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgHeartItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgHeartItem_descriptor_;
  metadata.reflection = MsgHeartItem_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgHeartItem

// optional string val = 1;
void MsgHeartItem::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgHeartItem::val() const {
  // @@protoc_insertion_point(field_get:MsgHeartItem.val)
  return val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgHeartItem::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgHeartItem.val)
}
 void MsgHeartItem::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgHeartItem.val)
}
 void MsgHeartItem::set_val(const char* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgHeartItem.val)
}
 ::std::string* MsgHeartItem::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:MsgHeartItem.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgHeartItem::release_val() {
  // @@protoc_insertion_point(field_release:MsgHeartItem.val)
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgHeartItem::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:MsgHeartItem.val)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgHeart::kNameFieldNumber;
const int MsgHeart::kItemFieldNumber;
const int MsgHeart::kGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgHeart::MsgHeart()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgHeart)
}

void MsgHeart::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  item_ = const_cast< ::MsgHeartItem*>(&::MsgHeartItem::default_instance());
}

MsgHeart::MsgHeart(const MsgHeart& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgHeart)
}

void MsgHeart::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  item_ = NULL;
  guid_ = 0;
}

MsgHeart::~MsgHeart() {
  // @@protoc_insertion_point(destructor:MsgHeart)
  SharedDtor();
}

void MsgHeart::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete item_;
  }
}

void MsgHeart::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgHeart::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgHeart_descriptor_;
}

const MsgHeart& MsgHeart::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_system_2eproto();
  return *default_instance_;
}

MsgHeart* MsgHeart::default_instance_ = NULL;

MsgHeart* MsgHeart::New(::google::protobuf::Arena* arena) const {
  MsgHeart* n = new MsgHeart;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgHeart::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgHeart)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && item_ != NULL) delete item_;
  item_ = NULL;
  guid_ = 0;
}

bool MsgHeart::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgHeart)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MsgHeartItem item = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MsgHeart.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_guid;
        break;
      }

      // optional int32 guid = 3;
      case 3: {
        if (tag == 24) {
         parse_guid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &guid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgHeart)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgHeart)
  return false;
#undef DO_
}

void MsgHeart::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgHeart)
  // optional .MsgHeartItem item = 1;
  if (this->has_item()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->item_, output);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgHeart.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // optional int32 guid = 3;
  if (this->guid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->guid(), output);
  }

  // @@protoc_insertion_point(serialize_end:MsgHeart)
}

::google::protobuf::uint8* MsgHeart::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgHeart)
  // optional .MsgHeartItem item = 1;
  if (this->has_item()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->item_, false, target);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgHeart.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // optional int32 guid = 3;
  if (this->guid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->guid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MsgHeart)
  return target;
}

int MsgHeart::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MsgHeart)
  int total_size = 0;

  // optional string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional .MsgHeartItem item = 1;
  if (this->has_item()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->item_);
  }

  // optional int32 guid = 3;
  if (this->guid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->guid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgHeart::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MsgHeart)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgHeart* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgHeart>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MsgHeart)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MsgHeart)
    MergeFrom(*source);
  }
}

void MsgHeart::MergeFrom(const MsgHeart& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MsgHeart)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_item()) {
    mutable_item()->::MsgHeartItem::MergeFrom(from.item());
  }
  if (from.guid() != 0) {
    set_guid(from.guid());
  }
}

void MsgHeart::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MsgHeart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgHeart::CopyFrom(const MsgHeart& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgHeart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgHeart::IsInitialized() const {

  return true;
}

void MsgHeart::Swap(MsgHeart* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgHeart::InternalSwap(MsgHeart* other) {
  name_.Swap(&other->name_);
  std::swap(item_, other->item_);
  std::swap(guid_, other->guid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgHeart::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgHeart_descriptor_;
  metadata.reflection = MsgHeart_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgHeart

// optional string name = 2;
void MsgHeart::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgHeart::name() const {
  // @@protoc_insertion_point(field_get:MsgHeart.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgHeart::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgHeart.name)
}
 void MsgHeart::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgHeart.name)
}
 void MsgHeart::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgHeart.name)
}
 ::std::string* MsgHeart::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:MsgHeart.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgHeart::release_name() {
  // @@protoc_insertion_point(field_release:MsgHeart.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgHeart::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:MsgHeart.name)
}

// optional .MsgHeartItem item = 1;
bool MsgHeart::has_item() const {
  return !_is_default_instance_ && item_ != NULL;
}
void MsgHeart::clear_item() {
  if (GetArenaNoVirtual() == NULL && item_ != NULL) delete item_;
  item_ = NULL;
}
const ::MsgHeartItem& MsgHeart::item() const {
  // @@protoc_insertion_point(field_get:MsgHeart.item)
  return item_ != NULL ? *item_ : *default_instance_->item_;
}
::MsgHeartItem* MsgHeart::mutable_item() {
  
  if (item_ == NULL) {
    item_ = new ::MsgHeartItem;
  }
  // @@protoc_insertion_point(field_mutable:MsgHeart.item)
  return item_;
}
::MsgHeartItem* MsgHeart::release_item() {
  // @@protoc_insertion_point(field_release:MsgHeart.item)
  
  ::MsgHeartItem* temp = item_;
  item_ = NULL;
  return temp;
}
void MsgHeart::set_allocated_item(::MsgHeartItem* item) {
  delete item_;
  item_ = item;
  if (item) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MsgHeart.item)
}

// optional int32 guid = 3;
void MsgHeart::clear_guid() {
  guid_ = 0;
}
 ::google::protobuf::int32 MsgHeart::guid() const {
  // @@protoc_insertion_point(field_get:MsgHeart.guid)
  return guid_;
}
 void MsgHeart::set_guid(::google::protobuf::int32 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:MsgHeart.guid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgTestBool::kTest1FieldNumber;
const int MsgTestBool::kTest2FieldNumber;
const int MsgTestBool::kTest3FieldNumber;
const int MsgTestBool::kTest4FieldNumber;
const int MsgTestBool::kTest5FieldNumber;
const int MsgTestBool::kTest6FieldNumber;
const int MsgTestBool::kTest7FieldNumber;
const int MsgTestBool::kTest8FieldNumber;
const int MsgTestBool::kTest9FieldNumber;
const int MsgTestBool::kTest10FieldNumber;
const int MsgTestBool::kTest11FieldNumber;
const int MsgTestBool::kTest12FieldNumber;
const int MsgTestBool::kTest13FieldNumber;
const int MsgTestBool::kTest14FieldNumber;
const int MsgTestBool::kTest15FieldNumber;
const int MsgTestBool::kTest16FieldNumber;
const int MsgTestBool::kTest17FieldNumber;
const int MsgTestBool::kTest18FieldNumber;
const int MsgTestBool::kTest19FieldNumber;
const int MsgTestBool::kTest20FieldNumber;
const int MsgTestBool::kTest21FieldNumber;
const int MsgTestBool::kTest22FieldNumber;
const int MsgTestBool::kTest23FieldNumber;
const int MsgTestBool::kTest24FieldNumber;
const int MsgTestBool::kTest25FieldNumber;
const int MsgTestBool::kTest26FieldNumber;
const int MsgTestBool::kTest27FieldNumber;
const int MsgTestBool::kTest28FieldNumber;
const int MsgTestBool::kTest29FieldNumber;
const int MsgTestBool::kTest30FieldNumber;
const int MsgTestBool::kTest31FieldNumber;
const int MsgTestBool::kTest32FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgTestBool::MsgTestBool()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgTestBool)
}

void MsgTestBool::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgTestBool::MsgTestBool(const MsgTestBool& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgTestBool)
}

void MsgTestBool::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  test_1_ = false;
  test_2_ = false;
  test_3_ = false;
  test_4_ = false;
  test_5_ = false;
  test_6_ = false;
  test_7_ = false;
  test_8_ = false;
  test_9_ = false;
  test_10_ = false;
  test_11_ = false;
  test_12_ = false;
  test_13_ = false;
  test_14_ = false;
  test_15_ = false;
  test_16_ = false;
  test_17_ = false;
  test_18_ = false;
  test_19_ = false;
  test_20_ = false;
  test_21_ = false;
  test_22_ = false;
  test_23_ = false;
  test_24_ = false;
  test_25_ = false;
  test_26_ = false;
  test_27_ = false;
  test_28_ = false;
  test_29_ = false;
  test_30_ = false;
  test_31_ = false;
  test_32_ = false;
}

MsgTestBool::~MsgTestBool() {
  // @@protoc_insertion_point(destructor:MsgTestBool)
  SharedDtor();
}

void MsgTestBool::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgTestBool::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgTestBool::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgTestBool_descriptor_;
}

const MsgTestBool& MsgTestBool::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_system_2eproto();
  return *default_instance_;
}

MsgTestBool* MsgTestBool::default_instance_ = NULL;

MsgTestBool* MsgTestBool::New(::google::protobuf::Arena* arena) const {
  MsgTestBool* n = new MsgTestBool;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgTestBool::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgTestBool)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MsgTestBool, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MsgTestBool*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(test_1_, test_8_);
  ZR_(test_9_, test_16_);
  ZR_(test_17_, test_24_);
  ZR_(test_25_, test_32_);

#undef ZR_HELPER_
#undef ZR_

}

bool MsgTestBool::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgTestBool)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool test_1 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_test_2;
        break;
      }

      // optional bool test_2 = 2;
      case 2: {
        if (tag == 16) {
         parse_test_2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_test_3;
        break;
      }

      // optional bool test_3 = 3;
      case 3: {
        if (tag == 24) {
         parse_test_3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_test_4;
        break;
      }

      // optional bool test_4 = 4;
      case 4: {
        if (tag == 32) {
         parse_test_4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_test_5;
        break;
      }

      // optional bool test_5 = 5;
      case 5: {
        if (tag == 40) {
         parse_test_5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_test_6;
        break;
      }

      // optional bool test_6 = 6;
      case 6: {
        if (tag == 48) {
         parse_test_6:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_6_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_test_7;
        break;
      }

      // optional bool test_7 = 7;
      case 7: {
        if (tag == 56) {
         parse_test_7:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_7_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_test_8;
        break;
      }

      // optional bool test_8 = 8;
      case 8: {
        if (tag == 64) {
         parse_test_8:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_8_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_test_9;
        break;
      }

      // optional bool test_9 = 9;
      case 9: {
        if (tag == 72) {
         parse_test_9:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_9_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_test_10;
        break;
      }

      // optional bool test_10 = 10;
      case 10: {
        if (tag == 80) {
         parse_test_10:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_10_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_test_11;
        break;
      }

      // optional bool test_11 = 11;
      case 11: {
        if (tag == 88) {
         parse_test_11:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_11_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_test_12;
        break;
      }

      // optional bool test_12 = 12;
      case 12: {
        if (tag == 96) {
         parse_test_12:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_12_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_test_13;
        break;
      }

      // optional bool test_13 = 13;
      case 13: {
        if (tag == 104) {
         parse_test_13:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_13_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(112)) goto parse_test_14;
        break;
      }

      // optional bool test_14 = 14;
      case 14: {
        if (tag == 112) {
         parse_test_14:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_14_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_test_15;
        break;
      }

      // optional bool test_15 = 15;
      case 15: {
        if (tag == 120) {
         parse_test_15:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_15_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_test_16;
        break;
      }

      // optional bool test_16 = 16;
      case 16: {
        if (tag == 128) {
         parse_test_16:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_16_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(136)) goto parse_test_17;
        break;
      }

      // optional bool test_17 = 17;
      case 17: {
        if (tag == 136) {
         parse_test_17:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_17_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(144)) goto parse_test_18;
        break;
      }

      // optional bool test_18 = 18;
      case 18: {
        if (tag == 144) {
         parse_test_18:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_18_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(152)) goto parse_test_19;
        break;
      }

      // optional bool test_19 = 19;
      case 19: {
        if (tag == 152) {
         parse_test_19:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_19_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(160)) goto parse_test_20;
        break;
      }

      // optional bool test_20 = 20;
      case 20: {
        if (tag == 160) {
         parse_test_20:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_20_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(168)) goto parse_test_21;
        break;
      }

      // optional bool test_21 = 21;
      case 21: {
        if (tag == 168) {
         parse_test_21:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_21_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(176)) goto parse_test_22;
        break;
      }

      // optional bool test_22 = 22;
      case 22: {
        if (tag == 176) {
         parse_test_22:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_22_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(184)) goto parse_test_23;
        break;
      }

      // optional bool test_23 = 23;
      case 23: {
        if (tag == 184) {
         parse_test_23:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_23_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(192)) goto parse_test_24;
        break;
      }

      // optional bool test_24 = 24;
      case 24: {
        if (tag == 192) {
         parse_test_24:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_24_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(200)) goto parse_test_25;
        break;
      }

      // optional bool test_25 = 25;
      case 25: {
        if (tag == 200) {
         parse_test_25:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_25_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(208)) goto parse_test_26;
        break;
      }

      // optional bool test_26 = 26;
      case 26: {
        if (tag == 208) {
         parse_test_26:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_26_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(216)) goto parse_test_27;
        break;
      }

      // optional bool test_27 = 27;
      case 27: {
        if (tag == 216) {
         parse_test_27:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_27_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(224)) goto parse_test_28;
        break;
      }

      // optional bool test_28 = 28;
      case 28: {
        if (tag == 224) {
         parse_test_28:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_28_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(232)) goto parse_test_29;
        break;
      }

      // optional bool test_29 = 29;
      case 29: {
        if (tag == 232) {
         parse_test_29:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_29_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(240)) goto parse_test_30;
        break;
      }

      // optional bool test_30 = 30;
      case 30: {
        if (tag == 240) {
         parse_test_30:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_30_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(248)) goto parse_test_31;
        break;
      }

      // optional bool test_31 = 31;
      case 31: {
        if (tag == 248) {
         parse_test_31:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_31_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(256)) goto parse_test_32;
        break;
      }

      // optional bool test_32 = 32;
      case 32: {
        if (tag == 256) {
         parse_test_32:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &test_32_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgTestBool)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgTestBool)
  return false;
#undef DO_
}

void MsgTestBool::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgTestBool)
  // optional bool test_1 = 1;
  if (this->test_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->test_1(), output);
  }

  // optional bool test_2 = 2;
  if (this->test_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->test_2(), output);
  }

  // optional bool test_3 = 3;
  if (this->test_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->test_3(), output);
  }

  // optional bool test_4 = 4;
  if (this->test_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->test_4(), output);
  }

  // optional bool test_5 = 5;
  if (this->test_5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->test_5(), output);
  }

  // optional bool test_6 = 6;
  if (this->test_6() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->test_6(), output);
  }

  // optional bool test_7 = 7;
  if (this->test_7() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->test_7(), output);
  }

  // optional bool test_8 = 8;
  if (this->test_8() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->test_8(), output);
  }

  // optional bool test_9 = 9;
  if (this->test_9() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->test_9(), output);
  }

  // optional bool test_10 = 10;
  if (this->test_10() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->test_10(), output);
  }

  // optional bool test_11 = 11;
  if (this->test_11() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->test_11(), output);
  }

  // optional bool test_12 = 12;
  if (this->test_12() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->test_12(), output);
  }

  // optional bool test_13 = 13;
  if (this->test_13() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(13, this->test_13(), output);
  }

  // optional bool test_14 = 14;
  if (this->test_14() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(14, this->test_14(), output);
  }

  // optional bool test_15 = 15;
  if (this->test_15() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(15, this->test_15(), output);
  }

  // optional bool test_16 = 16;
  if (this->test_16() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->test_16(), output);
  }

  // optional bool test_17 = 17;
  if (this->test_17() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(17, this->test_17(), output);
  }

  // optional bool test_18 = 18;
  if (this->test_18() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(18, this->test_18(), output);
  }

  // optional bool test_19 = 19;
  if (this->test_19() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(19, this->test_19(), output);
  }

  // optional bool test_20 = 20;
  if (this->test_20() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(20, this->test_20(), output);
  }

  // optional bool test_21 = 21;
  if (this->test_21() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(21, this->test_21(), output);
  }

  // optional bool test_22 = 22;
  if (this->test_22() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(22, this->test_22(), output);
  }

  // optional bool test_23 = 23;
  if (this->test_23() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(23, this->test_23(), output);
  }

  // optional bool test_24 = 24;
  if (this->test_24() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(24, this->test_24(), output);
  }

  // optional bool test_25 = 25;
  if (this->test_25() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(25, this->test_25(), output);
  }

  // optional bool test_26 = 26;
  if (this->test_26() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(26, this->test_26(), output);
  }

  // optional bool test_27 = 27;
  if (this->test_27() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(27, this->test_27(), output);
  }

  // optional bool test_28 = 28;
  if (this->test_28() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(28, this->test_28(), output);
  }

  // optional bool test_29 = 29;
  if (this->test_29() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(29, this->test_29(), output);
  }

  // optional bool test_30 = 30;
  if (this->test_30() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(30, this->test_30(), output);
  }

  // optional bool test_31 = 31;
  if (this->test_31() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(31, this->test_31(), output);
  }

  // optional bool test_32 = 32;
  if (this->test_32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(32, this->test_32(), output);
  }

  // @@protoc_insertion_point(serialize_end:MsgTestBool)
}

::google::protobuf::uint8* MsgTestBool::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgTestBool)
  // optional bool test_1 = 1;
  if (this->test_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->test_1(), target);
  }

  // optional bool test_2 = 2;
  if (this->test_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->test_2(), target);
  }

  // optional bool test_3 = 3;
  if (this->test_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->test_3(), target);
  }

  // optional bool test_4 = 4;
  if (this->test_4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->test_4(), target);
  }

  // optional bool test_5 = 5;
  if (this->test_5() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->test_5(), target);
  }

  // optional bool test_6 = 6;
  if (this->test_6() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->test_6(), target);
  }

  // optional bool test_7 = 7;
  if (this->test_7() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->test_7(), target);
  }

  // optional bool test_8 = 8;
  if (this->test_8() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->test_8(), target);
  }

  // optional bool test_9 = 9;
  if (this->test_9() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->test_9(), target);
  }

  // optional bool test_10 = 10;
  if (this->test_10() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->test_10(), target);
  }

  // optional bool test_11 = 11;
  if (this->test_11() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->test_11(), target);
  }

  // optional bool test_12 = 12;
  if (this->test_12() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->test_12(), target);
  }

  // optional bool test_13 = 13;
  if (this->test_13() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(13, this->test_13(), target);
  }

  // optional bool test_14 = 14;
  if (this->test_14() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(14, this->test_14(), target);
  }

  // optional bool test_15 = 15;
  if (this->test_15() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(15, this->test_15(), target);
  }

  // optional bool test_16 = 16;
  if (this->test_16() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(16, this->test_16(), target);
  }

  // optional bool test_17 = 17;
  if (this->test_17() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(17, this->test_17(), target);
  }

  // optional bool test_18 = 18;
  if (this->test_18() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(18, this->test_18(), target);
  }

  // optional bool test_19 = 19;
  if (this->test_19() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(19, this->test_19(), target);
  }

  // optional bool test_20 = 20;
  if (this->test_20() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(20, this->test_20(), target);
  }

  // optional bool test_21 = 21;
  if (this->test_21() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(21, this->test_21(), target);
  }

  // optional bool test_22 = 22;
  if (this->test_22() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(22, this->test_22(), target);
  }

  // optional bool test_23 = 23;
  if (this->test_23() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(23, this->test_23(), target);
  }

  // optional bool test_24 = 24;
  if (this->test_24() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(24, this->test_24(), target);
  }

  // optional bool test_25 = 25;
  if (this->test_25() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(25, this->test_25(), target);
  }

  // optional bool test_26 = 26;
  if (this->test_26() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(26, this->test_26(), target);
  }

  // optional bool test_27 = 27;
  if (this->test_27() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(27, this->test_27(), target);
  }

  // optional bool test_28 = 28;
  if (this->test_28() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(28, this->test_28(), target);
  }

  // optional bool test_29 = 29;
  if (this->test_29() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(29, this->test_29(), target);
  }

  // optional bool test_30 = 30;
  if (this->test_30() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(30, this->test_30(), target);
  }

  // optional bool test_31 = 31;
  if (this->test_31() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(31, this->test_31(), target);
  }

  // optional bool test_32 = 32;
  if (this->test_32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(32, this->test_32(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MsgTestBool)
  return target;
}

int MsgTestBool::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MsgTestBool)
  int total_size = 0;

  // optional bool test_1 = 1;
  if (this->test_1() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_2 = 2;
  if (this->test_2() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_3 = 3;
  if (this->test_3() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_4 = 4;
  if (this->test_4() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_5 = 5;
  if (this->test_5() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_6 = 6;
  if (this->test_6() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_7 = 7;
  if (this->test_7() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_8 = 8;
  if (this->test_8() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_9 = 9;
  if (this->test_9() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_10 = 10;
  if (this->test_10() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_11 = 11;
  if (this->test_11() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_12 = 12;
  if (this->test_12() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_13 = 13;
  if (this->test_13() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_14 = 14;
  if (this->test_14() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_15 = 15;
  if (this->test_15() != 0) {
    total_size += 1 + 1;
  }

  // optional bool test_16 = 16;
  if (this->test_16() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_17 = 17;
  if (this->test_17() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_18 = 18;
  if (this->test_18() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_19 = 19;
  if (this->test_19() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_20 = 20;
  if (this->test_20() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_21 = 21;
  if (this->test_21() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_22 = 22;
  if (this->test_22() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_23 = 23;
  if (this->test_23() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_24 = 24;
  if (this->test_24() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_25 = 25;
  if (this->test_25() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_26 = 26;
  if (this->test_26() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_27 = 27;
  if (this->test_27() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_28 = 28;
  if (this->test_28() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_29 = 29;
  if (this->test_29() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_30 = 30;
  if (this->test_30() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_31 = 31;
  if (this->test_31() != 0) {
    total_size += 2 + 1;
  }

  // optional bool test_32 = 32;
  if (this->test_32() != 0) {
    total_size += 2 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgTestBool::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MsgTestBool)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgTestBool* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgTestBool>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MsgTestBool)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MsgTestBool)
    MergeFrom(*source);
  }
}

void MsgTestBool::MergeFrom(const MsgTestBool& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MsgTestBool)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.test_1() != 0) {
    set_test_1(from.test_1());
  }
  if (from.test_2() != 0) {
    set_test_2(from.test_2());
  }
  if (from.test_3() != 0) {
    set_test_3(from.test_3());
  }
  if (from.test_4() != 0) {
    set_test_4(from.test_4());
  }
  if (from.test_5() != 0) {
    set_test_5(from.test_5());
  }
  if (from.test_6() != 0) {
    set_test_6(from.test_6());
  }
  if (from.test_7() != 0) {
    set_test_7(from.test_7());
  }
  if (from.test_8() != 0) {
    set_test_8(from.test_8());
  }
  if (from.test_9() != 0) {
    set_test_9(from.test_9());
  }
  if (from.test_10() != 0) {
    set_test_10(from.test_10());
  }
  if (from.test_11() != 0) {
    set_test_11(from.test_11());
  }
  if (from.test_12() != 0) {
    set_test_12(from.test_12());
  }
  if (from.test_13() != 0) {
    set_test_13(from.test_13());
  }
  if (from.test_14() != 0) {
    set_test_14(from.test_14());
  }
  if (from.test_15() != 0) {
    set_test_15(from.test_15());
  }
  if (from.test_16() != 0) {
    set_test_16(from.test_16());
  }
  if (from.test_17() != 0) {
    set_test_17(from.test_17());
  }
  if (from.test_18() != 0) {
    set_test_18(from.test_18());
  }
  if (from.test_19() != 0) {
    set_test_19(from.test_19());
  }
  if (from.test_20() != 0) {
    set_test_20(from.test_20());
  }
  if (from.test_21() != 0) {
    set_test_21(from.test_21());
  }
  if (from.test_22() != 0) {
    set_test_22(from.test_22());
  }
  if (from.test_23() != 0) {
    set_test_23(from.test_23());
  }
  if (from.test_24() != 0) {
    set_test_24(from.test_24());
  }
  if (from.test_25() != 0) {
    set_test_25(from.test_25());
  }
  if (from.test_26() != 0) {
    set_test_26(from.test_26());
  }
  if (from.test_27() != 0) {
    set_test_27(from.test_27());
  }
  if (from.test_28() != 0) {
    set_test_28(from.test_28());
  }
  if (from.test_29() != 0) {
    set_test_29(from.test_29());
  }
  if (from.test_30() != 0) {
    set_test_30(from.test_30());
  }
  if (from.test_31() != 0) {
    set_test_31(from.test_31());
  }
  if (from.test_32() != 0) {
    set_test_32(from.test_32());
  }
}

void MsgTestBool::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MsgTestBool)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgTestBool::CopyFrom(const MsgTestBool& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgTestBool)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgTestBool::IsInitialized() const {

  return true;
}

void MsgTestBool::Swap(MsgTestBool* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgTestBool::InternalSwap(MsgTestBool* other) {
  std::swap(test_1_, other->test_1_);
  std::swap(test_2_, other->test_2_);
  std::swap(test_3_, other->test_3_);
  std::swap(test_4_, other->test_4_);
  std::swap(test_5_, other->test_5_);
  std::swap(test_6_, other->test_6_);
  std::swap(test_7_, other->test_7_);
  std::swap(test_8_, other->test_8_);
  std::swap(test_9_, other->test_9_);
  std::swap(test_10_, other->test_10_);
  std::swap(test_11_, other->test_11_);
  std::swap(test_12_, other->test_12_);
  std::swap(test_13_, other->test_13_);
  std::swap(test_14_, other->test_14_);
  std::swap(test_15_, other->test_15_);
  std::swap(test_16_, other->test_16_);
  std::swap(test_17_, other->test_17_);
  std::swap(test_18_, other->test_18_);
  std::swap(test_19_, other->test_19_);
  std::swap(test_20_, other->test_20_);
  std::swap(test_21_, other->test_21_);
  std::swap(test_22_, other->test_22_);
  std::swap(test_23_, other->test_23_);
  std::swap(test_24_, other->test_24_);
  std::swap(test_25_, other->test_25_);
  std::swap(test_26_, other->test_26_);
  std::swap(test_27_, other->test_27_);
  std::swap(test_28_, other->test_28_);
  std::swap(test_29_, other->test_29_);
  std::swap(test_30_, other->test_30_);
  std::swap(test_31_, other->test_31_);
  std::swap(test_32_, other->test_32_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgTestBool::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgTestBool_descriptor_;
  metadata.reflection = MsgTestBool_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgTestBool

// optional bool test_1 = 1;
void MsgTestBool::clear_test_1() {
  test_1_ = false;
}
 bool MsgTestBool::test_1() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_1)
  return test_1_;
}
 void MsgTestBool::set_test_1(bool value) {
  
  test_1_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_1)
}

// optional bool test_2 = 2;
void MsgTestBool::clear_test_2() {
  test_2_ = false;
}
 bool MsgTestBool::test_2() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_2)
  return test_2_;
}
 void MsgTestBool::set_test_2(bool value) {
  
  test_2_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_2)
}

// optional bool test_3 = 3;
void MsgTestBool::clear_test_3() {
  test_3_ = false;
}
 bool MsgTestBool::test_3() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_3)
  return test_3_;
}
 void MsgTestBool::set_test_3(bool value) {
  
  test_3_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_3)
}

// optional bool test_4 = 4;
void MsgTestBool::clear_test_4() {
  test_4_ = false;
}
 bool MsgTestBool::test_4() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_4)
  return test_4_;
}
 void MsgTestBool::set_test_4(bool value) {
  
  test_4_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_4)
}

// optional bool test_5 = 5;
void MsgTestBool::clear_test_5() {
  test_5_ = false;
}
 bool MsgTestBool::test_5() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_5)
  return test_5_;
}
 void MsgTestBool::set_test_5(bool value) {
  
  test_5_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_5)
}

// optional bool test_6 = 6;
void MsgTestBool::clear_test_6() {
  test_6_ = false;
}
 bool MsgTestBool::test_6() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_6)
  return test_6_;
}
 void MsgTestBool::set_test_6(bool value) {
  
  test_6_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_6)
}

// optional bool test_7 = 7;
void MsgTestBool::clear_test_7() {
  test_7_ = false;
}
 bool MsgTestBool::test_7() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_7)
  return test_7_;
}
 void MsgTestBool::set_test_7(bool value) {
  
  test_7_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_7)
}

// optional bool test_8 = 8;
void MsgTestBool::clear_test_8() {
  test_8_ = false;
}
 bool MsgTestBool::test_8() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_8)
  return test_8_;
}
 void MsgTestBool::set_test_8(bool value) {
  
  test_8_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_8)
}

// optional bool test_9 = 9;
void MsgTestBool::clear_test_9() {
  test_9_ = false;
}
 bool MsgTestBool::test_9() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_9)
  return test_9_;
}
 void MsgTestBool::set_test_9(bool value) {
  
  test_9_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_9)
}

// optional bool test_10 = 10;
void MsgTestBool::clear_test_10() {
  test_10_ = false;
}
 bool MsgTestBool::test_10() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_10)
  return test_10_;
}
 void MsgTestBool::set_test_10(bool value) {
  
  test_10_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_10)
}

// optional bool test_11 = 11;
void MsgTestBool::clear_test_11() {
  test_11_ = false;
}
 bool MsgTestBool::test_11() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_11)
  return test_11_;
}
 void MsgTestBool::set_test_11(bool value) {
  
  test_11_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_11)
}

// optional bool test_12 = 12;
void MsgTestBool::clear_test_12() {
  test_12_ = false;
}
 bool MsgTestBool::test_12() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_12)
  return test_12_;
}
 void MsgTestBool::set_test_12(bool value) {
  
  test_12_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_12)
}

// optional bool test_13 = 13;
void MsgTestBool::clear_test_13() {
  test_13_ = false;
}
 bool MsgTestBool::test_13() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_13)
  return test_13_;
}
 void MsgTestBool::set_test_13(bool value) {
  
  test_13_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_13)
}

// optional bool test_14 = 14;
void MsgTestBool::clear_test_14() {
  test_14_ = false;
}
 bool MsgTestBool::test_14() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_14)
  return test_14_;
}
 void MsgTestBool::set_test_14(bool value) {
  
  test_14_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_14)
}

// optional bool test_15 = 15;
void MsgTestBool::clear_test_15() {
  test_15_ = false;
}
 bool MsgTestBool::test_15() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_15)
  return test_15_;
}
 void MsgTestBool::set_test_15(bool value) {
  
  test_15_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_15)
}

// optional bool test_16 = 16;
void MsgTestBool::clear_test_16() {
  test_16_ = false;
}
 bool MsgTestBool::test_16() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_16)
  return test_16_;
}
 void MsgTestBool::set_test_16(bool value) {
  
  test_16_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_16)
}

// optional bool test_17 = 17;
void MsgTestBool::clear_test_17() {
  test_17_ = false;
}
 bool MsgTestBool::test_17() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_17)
  return test_17_;
}
 void MsgTestBool::set_test_17(bool value) {
  
  test_17_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_17)
}

// optional bool test_18 = 18;
void MsgTestBool::clear_test_18() {
  test_18_ = false;
}
 bool MsgTestBool::test_18() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_18)
  return test_18_;
}
 void MsgTestBool::set_test_18(bool value) {
  
  test_18_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_18)
}

// optional bool test_19 = 19;
void MsgTestBool::clear_test_19() {
  test_19_ = false;
}
 bool MsgTestBool::test_19() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_19)
  return test_19_;
}
 void MsgTestBool::set_test_19(bool value) {
  
  test_19_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_19)
}

// optional bool test_20 = 20;
void MsgTestBool::clear_test_20() {
  test_20_ = false;
}
 bool MsgTestBool::test_20() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_20)
  return test_20_;
}
 void MsgTestBool::set_test_20(bool value) {
  
  test_20_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_20)
}

// optional bool test_21 = 21;
void MsgTestBool::clear_test_21() {
  test_21_ = false;
}
 bool MsgTestBool::test_21() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_21)
  return test_21_;
}
 void MsgTestBool::set_test_21(bool value) {
  
  test_21_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_21)
}

// optional bool test_22 = 22;
void MsgTestBool::clear_test_22() {
  test_22_ = false;
}
 bool MsgTestBool::test_22() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_22)
  return test_22_;
}
 void MsgTestBool::set_test_22(bool value) {
  
  test_22_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_22)
}

// optional bool test_23 = 23;
void MsgTestBool::clear_test_23() {
  test_23_ = false;
}
 bool MsgTestBool::test_23() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_23)
  return test_23_;
}
 void MsgTestBool::set_test_23(bool value) {
  
  test_23_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_23)
}

// optional bool test_24 = 24;
void MsgTestBool::clear_test_24() {
  test_24_ = false;
}
 bool MsgTestBool::test_24() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_24)
  return test_24_;
}
 void MsgTestBool::set_test_24(bool value) {
  
  test_24_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_24)
}

// optional bool test_25 = 25;
void MsgTestBool::clear_test_25() {
  test_25_ = false;
}
 bool MsgTestBool::test_25() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_25)
  return test_25_;
}
 void MsgTestBool::set_test_25(bool value) {
  
  test_25_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_25)
}

// optional bool test_26 = 26;
void MsgTestBool::clear_test_26() {
  test_26_ = false;
}
 bool MsgTestBool::test_26() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_26)
  return test_26_;
}
 void MsgTestBool::set_test_26(bool value) {
  
  test_26_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_26)
}

// optional bool test_27 = 27;
void MsgTestBool::clear_test_27() {
  test_27_ = false;
}
 bool MsgTestBool::test_27() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_27)
  return test_27_;
}
 void MsgTestBool::set_test_27(bool value) {
  
  test_27_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_27)
}

// optional bool test_28 = 28;
void MsgTestBool::clear_test_28() {
  test_28_ = false;
}
 bool MsgTestBool::test_28() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_28)
  return test_28_;
}
 void MsgTestBool::set_test_28(bool value) {
  
  test_28_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_28)
}

// optional bool test_29 = 29;
void MsgTestBool::clear_test_29() {
  test_29_ = false;
}
 bool MsgTestBool::test_29() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_29)
  return test_29_;
}
 void MsgTestBool::set_test_29(bool value) {
  
  test_29_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_29)
}

// optional bool test_30 = 30;
void MsgTestBool::clear_test_30() {
  test_30_ = false;
}
 bool MsgTestBool::test_30() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_30)
  return test_30_;
}
 void MsgTestBool::set_test_30(bool value) {
  
  test_30_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_30)
}

// optional bool test_31 = 31;
void MsgTestBool::clear_test_31() {
  test_31_ = false;
}
 bool MsgTestBool::test_31() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_31)
  return test_31_;
}
 void MsgTestBool::set_test_31(bool value) {
  
  test_31_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_31)
}

// optional bool test_32 = 32;
void MsgTestBool::clear_test_32() {
  test_32_ = false;
}
 bool MsgTestBool::test_32() const {
  // @@protoc_insertion_point(field_get:MsgTestBool.test_32)
  return test_32_;
}
 void MsgTestBool::set_test_32(bool value) {
  
  test_32_ = value;
  // @@protoc_insertion_point(field_set:MsgTestBool.test_32)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
